name: 'Warestack Workflow Copilot'
description:
  'Assists in automating workflow processes by providing AI-driven insights and
  automations.'
author: 'Dimitris Kargatzis <dimitris.kargatzis@warestacck.com>'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'monitor'
  color: 'white'

# Define your inputs here.
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  openai-api-key:
    description: 'OpenAI API key for querying GPT models'
    required: true
  workflow-run-id:
    description: 'ID of the completed workflow run'
    required: true

# Define your outputs here.
outputs:
  issue-url:
    description: 'URL of the created GitHub Issue if any issue is created'
  pr-url:
    description: 'URL of the created GitHub Pull Request if any PR is generated'

runs:
  using: node20
  main: dist/index.js
