name: Process Workflow Logs

on:
  workflow_run:
    workflows: ['Continuous Integration'] # Name of the primary workflow
    types:
      - completed

jobs:
  copilot-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_GITHUB_TOKEN }} # Token with workflows scope

      # Runs the action located at the root of the repository.
      - name: Run Local Action
        id: copilot
        uses: ./
        with:
          github-token: ${{ secrets.PAT_GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          workflow-run-id: ${{ github.event.workflow_run.id }} # ID of the completed workflow run
